all: 01_a_first_simple_program \
     02_a_small_variation \
     03_a_second_simple_program \
     04_another_data_type \
     05_area_of_a_circle \
     06_two_control_statements \
     07_the_for_loop \
     08_using_code_blocks \
     09_another_block_structure \
     10_semicolon_and_identation \
     11_keywords \
     12_identifiers


01_a_first_simple_program: 01_a_first_simple_program.cs Makefile
	mcs 01_a_first_simple_program.cs

02_a_small_variation: 02_a_small_variation.cs Makefile
	mcs 02_a_small_variation.cs

03_a_second_simple_program: 03_a_second_simple_program.cs Makefile
	mcs 03_a_second_simple_program.cs

04_another_data_type: 04_another_data_type.cs Makefile
	mcs 04_another_data_type.cs

05_area_of_a_circle: 05_area_of_a_circle.cs Makefile
	mcs 05_area_of_a_circle.cs

06_two_control_statements: 06_two_control_statements.cs Makefile
	mcs 06_two_control_statements.cs

07_the_for_loop: 07_the_for_loop.cs Makefile
	mcs 07_the_for_loop.cs

08_using_code_blocks: 08_using_code_blocks.cs Makefile
	mcs 08_using_code_blocks.cs

09_another_block_structure: 09_another_block_structure.cs Makefile
	mcs 09_another_block_structure.cs

10_semicolon_and_identation: 10_semicolon_and_identation.cs Makefile
	mcs 10_semicolon_and_identation.cs

11_keywords: 11_keywords.cs Makefile
	mcs 11_keywords.cs

12_identifiers: 12_identifiers.cs Makefile
	mcs 12_identifiers.cs


clean:
	rm -v 01_a_first_simple_program.exe \
          02_a_small_variation.exe \
          03_a_second_simple_program.exe \
          04_another_data_type.exe \
          05_area_of_a_circle.exe \
          06_two_control_statements.exe \
          07_the_for_loop.exe \
          08_using_code_blocks.exe \
          09_another_block_structure.exe \
          10_semicolon_and_identation.exe \
          11_keywords.exe \
          12_identifiers.exe
