all: 0_implementing_a_stack 1_implementing_a_queue

0_implementing_a_stack: 0_implementing_a_stack.cpp
	g++ -g -o 0_implementing_a_stack 0_implementing_a_stack.cpp

1_implementing_a_queue: 1_implementing_a_queue.cpp
	g++ -g -o 1_implementing_a_queue 1_implementing_a_queue.cpp

clean:
	rm -v 0_implementing_a_stack
	rm -v 1_implementing_a_queue
