all: ev16

ev1: ev1.cpp
	g++ -g -o ev1 ev1.cpp -lX11

ev2: ev2.cpp
	g++ -g -o ev2 ev2.cpp -lX11

ev3: ev3.cpp
	g++ -g -o ev3 ev3.cpp -lX11

ev4: ev4.cpp
	g++ -g -o ev4 ev4.cpp -lX11

ev5: ev5.cpp
	g++ -g -o ev5 ev5.cpp -lX11

ev6: ev6.cpp
	g++ -g -o ev6 ev6.cpp -lX11

ev7: ev7.cpp
	g++ -g -o ev7 ev7.cpp -lX11

ev8: ev8.cpp
	g++ -g -o ev8 ev8.cpp -lX11

ev9: ev9.cpp
	g++ -g -o ev9 ev9.cpp -lX11

ev10: ev10.cpp
	g++ -g -o ev10 ev10.cpp -lX11

ev11: ev11.cpp
	g++ -g -o ev11 ev11.cpp -lX11

ev12: ev12.cpp
	g++ -g -o ev12 ev12.cpp -lX11

ev13: ev13.cpp
	g++ -g -o ev13 ev13.cpp -lX11

ev14: ev14.cpp
	g++ -g -o ev14 ev14.cpp -lX11

ev15: ev15.cpp
	g++ -g -o ev15 ev15.cpp -lX11

ev16: ev16.cpp
	g++ -g -o ev16 ev16.cpp -lX11




clean:
	rm ev{1,2,3,4,5,6,7,8,9} \
       ev1{0,1,2,3,4,5,6,7,8,9}
