all: ev1

ev1: ev1.cpp
	g++ -g -o ev1 ev1.cpp -lX11

ev2: ev2.cpp
	g++ -g -o ev2 ev2.cpp -lX11

ev3: ev3.cpp
	g++ -g -o ev3 ev3.cpp -lX11

ev4: ev4.cpp
	g++ -g -o ev4 ev4.cpp -lX11

ev5: ev5.cpp
	g++ -g -o ev5 ev5.cpp -lX11

ev6: ev6.cpp
	g++ -g -o ev6 ev6.cpp -lX11

ev7: ev7.cpp
	g++ -g -o ev7 ev7.cpp -lX11

ev8: ev8.cpp
	g++ -g -o ev8 ev8.cpp -lX11




clean:
	rm ev{1,2,3,4,5,6,7,8,9} \
       ev1{0,1,2,3,4,5,6,7,8,9}
