all: 01_using_Console_Read \
     02_using_Console_ReadLine \
     03_using_Console_In \
     04_using_Console_ReadKey \
     05_using_Console_Out \
     06_using_FileStream_ReadByte \
     07_using_FileStream_ReadByte \
     08_using_FileStream_WriteByte \
     09_using_FileStream_toCopyFile \
     10_using_StreamWriter_Write \
     11_using_StreamWriter_Write \
     12_using_StreamReader_ReadLine \
     13_using_Console_SetOut \
     14_using_BinaryReader_and_Writer \
     15_using_BinaryReader_and_Writer \
     16_using_FileStream_Seek \
     17_using_MemoryStream \
     18_using_StringReader_and_Writer \
     19_using_File_Copy \
     20_using_File_Exists \
     21_using_Int32_forStringConversion


01_using_Console_Read: 01_using_Console_Read.cs Makefile
	mcs 01_using_Console_Read.cs

02_using_Console_ReadLine: 02_using_Console_ReadLine.cs Makefile
	mcs 02_using_Console_ReadLine.cs

03_using_Console_In: 03_using_Console_In.cs Makefile
	mcs 03_using_Console_In.cs

04_using_Console_ReadKey: 04_using_Console_ReadKey.cs Makefile
	mcs 04_using_Console_ReadKey.cs

05_using_Console_Out: 05_using_Console_Out.cs Makefile
	mcs 05_using_Console_Out.cs

06_using_FileStream_ReadByte: 06_using_FileStream_ReadByte.cs Makefile
	mcs 06_using_FileStream_ReadByte.cs

07_using_FileStream_ReadByte: 07_using_FileStream_ReadByte.cs Makefile
	mcs 07_using_FileStream_ReadByte.cs

08_using_FileStream_WriteByte: 08_using_FileStream_WriteByte.cs Makefile
	mcs 08_using_FileStream_WriteByte.cs

09_using_FileStream_toCopyFile: 09_using_FileStream_toCopyFile.cs Makefile
	mcs 09_using_FileStream_toCopyFile.cs

10_using_StreamWriter_Write: 10_using_StreamWriter_Write.cs Makefile
	mcs 10_using_StreamWriter_Write.cs

11_using_StreamWriter_Write: 11_using_StreamWriter_Write.cs Makefile
	mcs 11_using_StreamWriter_Write.cs

12_using_StreamReader_ReadLine: 12_using_StreamReader_ReadLine.cs Makefile
	mcs 12_using_StreamReader_ReadLine.cs

13_using_Console_SetOut: 13_using_Console_SetOut.cs Makefile
	mcs 13_using_Console_SetOut.cs

14_using_BinaryReader_and_Writer: 14_using_BinaryReader_and_Writer.cs Makefile
	mcs 14_using_BinaryReader_and_Writer.cs

15_using_BinaryReader_and_Writer: 15_using_BinaryReader_and_Writer.cs Makefile
	mcs 15_using_BinaryReader_and_Writer.cs

16_using_FileStream_Seek: 16_using_FileStream_Seek.cs Makefile
	mcs 16_using_FileStream_Seek.cs

17_using_MemoryStream: 17_using_MemoryStream.cs Makefile
	mcs 17_using_MemoryStream.cs

18_using_StringReader_and_Writer: 18_using_StringReader_and_Writer.cs Makefile
	mcs 18_using_StringReader_and_Writer.cs

19_using_File_Copy: 19_using_File_Copy.cs Makefile
	mcs 19_using_File_Copy.cs

20_using_File_Exists: 20_using_File_Exists.cs Makefile
	mcs 20_using_File_Exists.cs

21_using_Int32_forStringConversion: 21_using_Int32_forStringConversion.cs Makefile
	mcs 21_using_Int32_forStringConversion.cs


clean:
	rm -v 01_using_Console_Read.exe \
          02_using_Console_ReadLine.exe \
          03_using_Console_In.exe \
          04_using_Console_ReadKey.exe \
          05_using_Console_Out.exe \
          06_using_FileStream_ReadByte.exe \
          07_using_FileStream_ReadByte.exe \
          08_using_FileStream_WriteByte.exe \
          09_using_FileStream_toCopyFile.exe \
          10_using_StreamWriter_Write.exe \
          11_using_StreamWriter_Write.exe \
          12_using_StreamReader_ReadLine.exe \
          13_using_Console_SetOut.exe \
          14_using_BinaryReader_and_Writer.exe \
          15_using_BinaryReader_and_Writer.exe \
          16_using_FileStream_Seek.exe \
          17_using_MemoryStream.exe \
          18_using_StringReader_and_Writer.exe \
          19_using_File_Copy.exe \
          20_using_File_Exists.exe \
          21_using_Int32_forStringConversion.exe
