all: 01_io_with_streams \
     02_Stream \
     03_Console \
     04_FileStream_with_bytes \
     05_FileStream_with_chars \
     06_redirection \
     07_read_write_binary \
     08_random_file_access \
     09_MemoryStream \
     10_String_streams \
     11_File \
     12_String_conversion


01_io_with_streams: 01_io_with_streams.cs Makefile
	mcs 01_io_with_streams.cs

02_Stream: 02_Stream.cs Makefile
	mcs 02_Stream.cs

03_Console: 03_Console.cs Makefile
	mcs 03_Console.cs

04_FileStream_with_bytes: 04_FileStream_with_bytes.cs Makefile
	mcs 04_FileStream_with_bytes.cs

05_FileStream_with_chars: 05_FileStream_with_chars.cs Makefile
	mcs 05_FileStream_with_chars.cs

06_redirection: 06_redirection.cs Makefile
	mcs 06_redirection.cs

07_read_write_binary: 07_read_write_binary.cs Makefile
	mcs 07_read_write_binary.cs

08_random_file_access: 08_random_file_access.cs Makefile
	mcs 08_random_file_access.cs

09_MemoryStream: 09_MemoryStream.cs Makefile
	mcs 09_MemoryStream.cs

10_String_streams: 10_String_streams.cs Makefile
	mcs 10_String_streams.cs

11_File: 11_File.cs Makefile
	mcs 11_File.cs

12_String_conversion: 12_String_conversion.cs Makefile
	mcs 12_String_conversion.cs


clean:
	rm -v 01_io_with_streams.exe \
          02_Stream.exe \
          03_Console.exe \
          04_FileStream_with_bytes.exe \
          05_FileStream_with_chars.exe \
          06_redirection.exe \
          07_read_write_binary.exe \
          08_random_file_access.exe \
          09_MemoryStream.exe \
          10_String_streams.exe \
          11_File.exe \
          12_String_conversion.exe
