all: 01_if_else_if \
     02_switch \
     03_for \
     04_while \
     05_do_while \
     06_foreach \
     07_break \
     08_continue \
     09_goto


01_if_else_if: 01_if_else_if.cs Makefile
	mcs 01_if_else_if.cs

02_switch: 02_switch.cs Makefile
	mcs 02_switch.cs

03_for: 03_for.cs Makefile
	mcs 03_for.cs

04_while: 04_while.cs Makefile
	mcs 04_while.cs

05_do_while: 05_do_while.cs Makefile
	mcs 05_do_while.cs

06_foreach: 06_foreach.cs Makefile
	mcs 06_foreach.cs

07_break: 07_break.cs Makefile
	mcs 07_break.cs

08_continue: 08_continue.cs Makefile
	mcs 08_continue.cs

09_goto: 09_goto.cs Makefile
	mcs 09_goto.cs


clean: 01_if_else_if.exe \
       02_switch.exe \
       03_for.exe \
       04_while.exe \
       05_do_while.exe \
       06_foreach.exe \
       07_break.exe \
       08_continue.exe \
       09_goto.exe
