all: 01_Thread \
     02_Thread.Name \
     03_create_multiple_threads \
     04_Thread.IsAlive \
     05_Thread.Join \
     06_Thread.Start \
     07_Thread.ThreadPriority \
     08_lock \
     09_lock \
     10_Monitor.Pulse \
     11_MethodImplAttribute \
     12_Mutex \
     13_Semaphore \
     14_ManualResetEvent \
     15_Interlocked \
     16_Thread.Abort \
     17_Thread.Abort \
     18_Thread.ResetAbort \
     19_Thread.CurrentThread \
     20_Process.Start


01_Thread: 01_Thread.cs Makefile
	mcs 01_Thread.cs

02_Thread.Name: 02_Thread.Name.cs Makefile
	mcs 02_Thread.Name.cs

03_create_multiple_threads: 03_create_multiple_threads.cs Makefile
	mcs 03_create_multiple_threads.cs

04_Thread.IsAlive: 04_Thread.IsAlive.cs Makefile
	mcs 04_Thread.IsAlive.cs

05_Thread.Join: 05_Thread.Join.cs Makefile
	mcs 05_Thread.Join.cs

06_Thread.Start: 06_Thread.Start.cs Makefile
	mcs 06_Thread.Start.cs

07_Thread.ThreadPriority: 07_Thread.ThreadPriority.cs Makefile
	mcs 07_Thread.ThreadPriority.cs

08_lock: 08_lock.cs Makefile
	mcs 08_lock.cs

09_lock: 09_lock.cs Makefile
	mcs 09_lock.cs

10_Monitor.Pulse: 10_Monitor.Pulse.cs Makefile
	mcs 10_Monitor.Pulse.cs

11_MethodImplAttribute: 11_MethodImplAttribute.cs Makefile
	mcs 11_MethodImplAttribute.cs

12_Mutex: 12_Mutex.cs Makefile
	mcs 12_Mutex.cs

13_Semaphore: 13_Semaphore.cs Makefile
	mcs 13_Semaphore.cs

14_ManualResetEvent: 14_ManualResetEvent.cs Makefile
	mcs 14_ManualResetEvent.cs

15_Interlocked: 15_Interlocked.cs Makefile
	mcs 15_Interlocked.cs

16_Thread.Abort: 16_Thread.Abort.cs Makefile
	mcs 16_Thread.Abort.cs

17_Thread.Abort: 17_Thread.Abort.cs Makefile
	mcs 17_Thread.Abort.cs

18_Thread.ResetAbort: 18_Thread.ResetAbort.cs Makefile
	mcs 18_Thread.ResetAbort.cs

19_Thread.CurrentThread: 19_Thread.CurrentThread.cs Makefile
	mcs 19_Thread.CurrentThread.cs

20_Process.Start: 20_Process.Start.cs Makefile
	mcs 20_Process.Start.cs


clean:
	rm -v 01_Thread.exe \
          02_Thread.Name.exe \
          03_create_multiple_threads.exe \
          04_Thread.IsAlive.exe \
          05_Thread.Join.exe \
          06_Thread.Start.exe \
          07_Thread.ThreadPriority.exe \
          08_lock.exe \
          09_lock.exe \
          10_Monitor.Pulse.exe \
          11_MethodImplAttribute.exe \
          12_Mutex.exe \
          13_Semaphore.exe \
          14_ManualResetEvent.exe \
          15_Interlocked.exe \
          16_Thread.Abort.exe \
          17_Thread.Abort.exe \
          18_Thread.ResetAbort.exe \
          19_Thread.CurrentThread.exe \
          20_Process.Start.exe
