all: 01_Task \
     02_Task.Start \
     03_Task.CurrentId \
     04_Task.Wait \
     05_Task_as_lambda \
     06_Task.ContinueWith \
     07_Task.Result \
     08_CancellationToken \
     09_Parallel.Invoke \
     10_Parallel.Invoke_as_lambda \
     11_Parallel.For \
     12_sequential_and_parallel_time \
     13_ParallelLoopResult \
     14_ParallelLoopResult \
     15_PLINQ_AsParallel \
     16_PLINQ_AsParallel_WithCancellation


01_Task: 01_Task.cs Makefile
	mcs 01_Task.cs

02_Task.Start: 02_Task.Start.cs Makefile
	mcs 02_Task.Start.cs

03_Task.CurrentId: 03_Task.CurrentId.cs Makefile
	mcs 03_Task.CurrentId.cs

04_Task.Wait: 04_Task.Wait.cs Makefile
	mcs 04_Task.Wait.cs

05_Task_as_lambda: 05_Task_as_lambda.cs Makefile
	mcs 05_Task_as_lambda.cs

06_Task.ContinueWith: 06_Task.ContinueWith.cs Makefile
	mcs 06_Task.ContinueWith.cs

07_Task.Result: 07_Task.Result.cs Makefile
	mcs 07_Task.Result.cs

08_CancellationToken: 08_CancellationToken.cs Makefile
	mcs 08_CancellationToken.cs

09_Parallel.Invoke: 09_Parallel.Invoke.cs Makefile
	mcs 09_Parallel.Invoke.cs

10_Parallel.Invoke_as_lambda: 10_Parallel.Invoke_as_lambda.cs Makefile
	mcs 10_Parallel.Invoke_as_lambda.cs

11_Parallel.For: 11_Parallel.For.cs Makefile
	mcs 11_Parallel.For.cs

12_sequential_and_parallel_time: 12_sequential_and_parallel_time.cs Makefile
	mcs 12_sequential_and_parallel_time.cs

13_ParallelLoopResult: 13_ParallelLoopResult.cs Makefile
	mcs 13_ParallelLoopResult.cs

14_ParallelLoopResult: 14_ParallelLoopResult.cs Makefile
	mcs 14_ParallelLoopResult.cs

15_PLINQ_AsParallel: 15_PLINQ_AsParallel.cs Makefile
	mcs 15_PLINQ_AsParallel.cs

16_PLINQ_AsParallel_WithCancellation: 16_PLINQ_AsParallel_WithCancellation.cs Makefile
	mcs 16_PLINQ_AsParallel_WithCancellation.cs


clean:
	rm -v 01_Task.cs
          02_Task.Start.cs
          03_Task.CurrentId.cs
          04_Task.Wait.cs
          05_Task_as_lambda.cs
          06_Task.ContinueWith.cs
          07_Task.Result.cs
          08_CancellationToken.cs
          09_Parallel.Invoke.cs
          10_Parallel.Invoke_as_lambda.cs
          11_Parallel.For.cs
          12_sequential_and_parallel_time.cs
          13_ParallelLoopResult.cs
          14_ParallelLoopResult.cs
          15_PLINQ_AsParallel.cs
          16_PLINQ_AsParallel_WithCancellation.cs
