/*
  See README.txt for an extensive explanation.

  export PATH=/usr/lib64/qt5/bin:$PATH
  qmake -project -o addressbook.pro

  # Add, remove, edit source, headers and design ui files.
  qtcreator addressbook.pro &

  # When done, create the makefile, build and run the executable.
  qmake -makefile -o Makefile "QT+=widgets" addressbook.pro
  make

  # check for moc_ and ui_ prefixed autogenerated files.
  ./addressbook
 */

#include "listdialog.h"
#include <QtWidgets/QApplication>


int main(int argc, char** argv)
{
    QApplication app(argc, argv);
    ListDialog dlg;

    dlg.show();

    return app.exec();
}
