all: 01_exception_fundamentals \
     02_IndexOutOfRangeException \
     03_uncaught_exception \
     04_abnormal_termination \
     05_DivideByZeroException \
     06_multiple_catch_clauses \
     07_catch_all \
     08_nested_try_blocks \
     09_throw \
     10_rethrowing_an_exception \
     11_finally \
     12_the_Exception_class \
     13_NullReferenceException \
     14_deriving_Exception_class \
     15_catching_derived_exceptions \
     16_checked_and_unchecked \
     17_checked_with_blocks


01_exception_fundamentals: 01_exception_fundamentals.cs Makefile
	mcs 01_exception_fundamentals.cs

02_IndexOutOfRangeException: 02_IndexOutOfRangeException.cs Makefile
	mcs 02_IndexOutOfRangeException.cs

03_uncaught_exception: 03_uncaught_exception.cs Makefile
	mcs 03_uncaught_exception.cs

04_abnormal_termination: 04_abnormal_termination.cs Makefile
	mcs 04_abnormal_termination.cs

05_DivideByZeroException: 05_DivideByZeroException.cs Makefile
	mcs 05_DivideByZeroException.cs

06_multiple_catch_clauses: 06_multiple_catch_clauses.cs Makefile
	mcs 06_multiple_catch_clauses.cs

07_catch_all: 07_catch_all.cs Makefile
	mcs 07_catch_all.cs

08_nested_try_blocks: 08_nested_try_blocks.cs Makefile
	mcs 08_nested_try_blocks.cs

09_throw: 09_throw.cs Makefile
	mcs 09_throw.cs

10_rethrowing_an_exception: 10_rethrowing_an_exception.cs Makefile
	mcs 10_rethrowing_an_exception.cs

11_finally: 11_finally.cs Makefile
	mcs 11_finally.cs

12_the_Exception_class: 12_the_Exception_class.cs Makefile
	mcs 12_the_Exception_class.cs

13_NullReferenceException: 13_NullReferenceException.cs Makefile
	mcs 13_NullReferenceException.cs

14_deriving_Exception_class: 14_deriving_Exception_class.cs Makefile
	mcs 14_deriving_Exception_class.cs

15_catching_derived_exceptions: 15_catching_derived_exceptions.cs Makefile
	mcs 15_catching_derived_exceptions.cs

16_checked_and_unchecked: 16_checked_and_unchecked.cs Makefile
	mcs 16_checked_and_unchecked.cs

17_checked_with_blocks: 17_checked_with_blocks.cs Makefile
	mcs 17_checked_with_blocks.cs


clean:
	rm -v 01_exception_fundamentals.exe \
          02_IndexOutOfRangeException.exe \
          03_uncaught_exception.exe \
          04_abnormal_termination.exe \
          05_DivideByZeroException.exe \
          06_multiple_catch_clauses.exe \
          07_catch_all.exe \
          08_nested_try_blocks.exe \
          09_throw.exe \
          10_rethrowing_an_exception.exe \
          11_finally.exe \
          12_the_Exception_class.exe \
          13_NullReferenceException.exe \
          14_deriving_Exception_class.exe \
          15_catching_derived_exceptions.exe \
          16_checked_and_unchecked.exe \
          17_checked_with_blocks.exe
