all: 01_the_Exception_class \
     02_fundamentals \
     03_uncaught_exception \
     04_handle_errors \
     05_multiple_catch \
     06_catch_all_exceptions \
     07_nesting_try_blocks \
     08_throw \
     09_finally \
     10_the_Exception_class \
     11_deriving_exception_classes \
     12_catching_derived_exception \
     13_checked_and_unchecked


01_the_Exception_class: 01_the_Exception_class.cs Makefile
	mcs 01_the_Exception_class.cs

02_fundamentals: 02_fundamentals.cs Makefile
	mcs 02_fundamentals.cs

03_uncaught_exception: 03_uncaught_exception.cs Makefile
	mcs 03_uncaught_exception.cs

04_handle_errors: 04_handle_errors.cs Makefile
	mcs 04_handle_errors.cs

05_multiple_catch: 05_multiple_catch.cs Makefile
	mcs 05_multiple_catch.cs

06_catch_all_exceptions: 06_catch_all_exceptions.cs Makefile
	mcs 06_catch_all_exceptions.cs

07_nesting_try_blocks: 07_nesting_try_blocks.cs Makefile
	mcs 07_nesting_try_blocks.cs

08_throw: 08_throw.cs Makefile
	mcs 08_throw.cs

09_finally: 09_finally.cs Makefile
	mcs 09_finally.cs

10_the_Exception_class: 10_the_Exception_class.cs Makefile
	mcs 10_the_Exception_class.cs

11_deriving_exception_classes: 11_deriving_exception_classes.cs Makefile
	mcs 11_deriving_exception_classes.cs

12_catching_derived_exception: 12_catching_derived_exception.cs Makefile
	mcs 12_catching_derived_exception.cs

13_checked_and_unchecked: 13_checked_and_unchecked.cs Makefile
	mcs 13_checked_and_unchecked.cs



clean:
	rm -v 01_the_Exception_class.exe \
          02_fundamentals.exe \
          03_uncaught_exception.exe \
          04_handle_errors.exe \
          05_multiple_catch.exe \
          06_catch_all_exceptions.exe \
          07_nesting_try_blocks.exe \
          08_throw.exe \
          09_finally.exe \
          10_the_Exception_class.exe \
          11_deriving_exception_classes.exe \
          12_catching_derived_exception.exe \
          13_checked_and_unchecked.exe
