all: 01_String.Compare \
     02_String.Concat \
     03_String.Concat \
     04_String.IndexOf \
     05_String.Contains \
     06_String.Join \
     07_String.Split \
     08_String.PadLeft \
     09_String.Replace \
     10_String.Substring \
     11_formatting \
     12_formatting_arguments \
     13_String.Format \
     14_String.Format \
     15_String.ToString \
     16_formatting_custom \
     17_formatting_date_time \
     18_clock_sample \
     19_formatting_custom_date_time \
     20_formatting_time_span \
     21_formatting_enum


01_String.Compare: 01_String.Compare.cs Makefile
	mcs 01_String.Compare.cs

02_String.Concat: 02_String.Concat.cs Makefile
	mcs 02_String.Concat.cs

03_String.Concat: 03_String.Concat.cs Makefile
	mcs 03_String.Concat.cs

04_String.IndexOf: 04_String.IndexOf.cs Makefile
	mcs 04_String.IndexOf.cs

05_String.Contains: 05_String.Contains.cs Makefile
	mcs 05_String.Contains.cs

06_String.Join: 06_String.Join.cs Makefile
	mcs 06_String.Join.cs

07_String.Split: 07_String.Split.cs Makefile
	mcs 07_String.Split.cs

08_String.PadLeft: 08_String.PadLeft.cs Makefile
	mcs 08_String.PadLeft.cs

09_String.Replace: 09_String.Replace.cs Makefile
	mcs 09_String.Replace.cs

10_String.Substring: 10_String.Substring.cs Makefile
	mcs 10_String.Substring.cs

11_formatting: 11_formatting.cs Makefile
	mcs 11_formatting.cs

12_formatting_arguments: 12_formatting_arguments.cs Makefile
	mcs 12_formatting_arguments.cs

13_String.Format: 13_String.Format.cs Makefile
	mcs 13_String.Format.cs

14_String.Format: 14_String.Format.cs Makefile
	mcs 14_String.Format.cs

15_String.ToString: 15_String.ToString.cs Makefile
	mcs 15_String.ToString.cs

16_formatting_custom: 16_formatting_custom.cs Makefile
	mcs 16_formatting_custom.cs

17_formatting_date_time: 17_formatting_date_time.cs Makefile
	mcs 17_formatting_date_time.cs

18_clock_sample: 18_clock_sample.cs Makefile
	mcs 18_clock_sample.cs

19_formatting_custom_date_time: 19_formatting_custom_date_time.cs Makefile
	mcs 19_formatting_custom_date_time.cs

20_formatting_time_span: 20_formatting_time_span.cs Makefile
	mcs 20_formatting_time_span.cs

21_formatting_enum: 21_formatting_enum.cs Makefile
	mcs 21_formatting_enum.cs


clean:
	rm -v 01_String.Compare.exe \
          02_String.Concat.exe \
          03_String.Concat.exe \
          04_String.IndexOf.exe \
          05_String.Contains.exe \
          06_String.Join.exe \
          07_String.Split.exe \
          08_String.PadLeft.exe \
          09_String.Replace.exe \
          10_String.Substring.exe \
          11_formatting.exe \
          12_formatting_arguments.exe \
          13_String.Format.exe \
          14_String.Format.exe \
          15_String.ToString.exe \
          16_formatting_custom.exe \
          17_formatting_date_time.exe \
          18_clock_sample.exe \
          19_formatting_custom_date_time.exe \
          20_formatting_time_span.exe \
          21_formatting_enum.exe
