all:  01_interfaces \
      02_implement_additional_members \
      03_example_Primes \
      04_reference_to_interface \
      05_interface_properties \
      06_interface_indexers \
      07_interface_inheritance \
      08_interface_inheritance_member_hidding \
      09_explicit_implementation \
      10_removing_ambiguity \
      11_interface_vs_abstract_class \
      12_structures \
      13_struct_assignament \
      14_class_asignament_in_comparison \
      15_example_PacketHeader \
      16_enumerations \
      17_example_Conveyor


01_interfaces: 01_interfaces.cs Makefile
	mcs 01_interfaces.cs

02_implement_additional_members: 02_implement_additional_members.cs Makefile
	mcs 02_implement_additional_members.cs

03_example_Primes: 03_example_Primes.cs Makefile
	mcs 03_example_Primes.cs

04_reference_to_interface: 04_reference_to_interface.cs Makefile
	mcs 04_reference_to_interface.cs

05_interface_properties: 05_interface_properties.cs Makefile
	mcs 05_interface_properties.cs

06_interface_indexers: 06_interface_indexers.cs Makefile
	mcs 06_interface_indexers.cs

07_interface_inheritance: 07_interface_inheritance.cs Makefile
	mcs 07_interface_inheritance.cs

08_interface_inheritance_member_hidding: 08_interface_inheritance_member_hidding.cs Makefile
	mcs 08_interface_inheritance_member_hidding.cs

09_explicit_implementation: 09_explicit_implementation.cs Makefile
	#mcs 09_explicit_implementation.cs
	echo " // Error, IsOdd not exposed."

10_removing_ambiguity: 10_removing_ambiguity.cs Makefile
	mcs 10_removing_ambiguity.cs

11_interface_vs_abstract_class: 11_interface_vs_abstract_class.cs Makefile
	mcs 11_interface_vs_abstract_class.cs

12_structures: 12_structures.cs Makefile
	mcs 12_structures.cs

13_struct_assignament: 13_struct_assignament.cs Makefile
	mcs 13_struct_assignament.cs

14_class_asignament_in_comparison: 14_class_asignament_in_comparison.cs Makefile
	mcs 14_class_asignament_in_comparison.cs

15_example_PacketHeader: 15_example_PacketHeader.cs Makefile
	mcs 15_example_PacketHeader.cs

16_enumerations: 16_enumerations.cs Makefile
	mcs 16_enumerations.cs

17_example_Conveyor: 17_example_Conveyor.cs Makefile
	mcs 17_example_Conveyor.cs


clean:
	rm -v 01_interfaces.exe \
          02_implement_additional_members.exe \
          03_example_Primes.exe \
          04_reference_to_interface.exe \
          05_interface_properties.exe \
          06_interface_indexers.exe \
          07_interface_inheritance.exe \
          08_interface_inheritance_member_hidding.exe \
          09_explicit_implementation.exe \
          10_removing_ambiguity.exe \
          11_interface_vs_abstract_class.exe \
          12_structures.exe \
          13_struct_assignament.exe \
          14_class_asignament_in_comparison.exe \
          15_example_PacketHeader.exe \
          16_enumerations.exe \
          17_example_Conveyor.exe
