all: 01_interfaces \
     02_using_interfaces \
     03_interface_properties \
     04_interface_indexers \
     05_interfaces_can_be_inherited \
     06_name_hiding \
     07_explicit_implementations \
     08_interface_vs_abstract_class \
     09_dotnet_standard_interfaces \
     10_structures \
     11_enumerations


01_interfaces: 01_interfaces.cs Makefile
	mcs 01_interfaces.cs

02_using_interfaces: 02_using_interfaces.cs Makefile
	mcs 02_using_interfaces.cs

03_interface_properties: 03_interface_properties.cs Makefile
	mcs 03_interface_properties.cs

04_interface_indexers: 04_interface_indexers.cs Makefile
	mcs 04_interface_indexers.cs

05_interfaces_can_be_inherited: 05_interfaces_can_be_inherited.cs Makefile
	mcs 05_interfaces_can_be_inherited.cs

06_name_hiding: 06_name_hiding.cs Makefile
	mcs 06_name_hiding.cs

07_explicit_implementations: 07_explicit_implementations.cs Makefile
	mcs 07_explicit_implementations.cs

08_interface_vs_abstract_class: 08_interface_vs_abstract_class.cs Makefile
	mcs 08_interface_vs_abstract_class.cs

09_dotnet_standard_interfaces: 09_dotnet_standard_interfaces.cs Makefile
	mcs 09_dotnet_standard_interfaces.cs

10_structures: 10_structures.cs Makefile
	mcs 10_structures.cs

11_enumerations: 11_enumerations.cs Makefile
	mcs 11_enumerations.cs


clean:
	rm -v 01_interfaces.exe \
          02_using_interfaces.exe \
          03_interface_properties.exe \
          04_interface_indexers.exe \
          05_interfaces_can_be_inherited.exe \
          06_name_hiding.exe \
          07_explicit_implementations.exe \
          08_interface_vs_abstract_class.exe \
          09_dotnet_standard_interfaces.exe \
          10_structures.exe \
          11_enumerations.exe
