all: winattr9


winattr1: winattr1.cpp
	g++ -g -o winattr1 winattr1.cpp -lX11

winattr2: winattr2.cpp
	g++ -g -o winattr2 winattr2.cpp -lX11

winattr3: winattr3.cpp
	g++ -g -o winattr3 winattr3.cpp -lX11

winattr4: winattr4.cpp
	g++ -g -o winattr4 winattr4.cpp -lX11

winattr5: winattr5.cpp
	g++ -g -o winattr5 winattr5.cpp -lX11

winattr6: winattr6.cpp
	g++ -g -o winattr6 winattr6.cpp -lX11

winattr7: winattr7.cpp
	g++ -g -o winattr7 winattr7.cpp -lX11

winattr8: winattr8.cpp
	g++ -g -o winattr8 winattr8.cpp -lX11

winattr9: winattr9.cpp
	g++ -g -o winattr9 winattr9.cpp -lX11
