all: winattr4


winattr1: winattr1.cpp
	g++ -g -o winattr1 winattr1.cpp -lX11

winattr2: winattr2.cpp
	g++ -g -o winattr2 winattr2.cpp -lX11

winattr3: winattr3.cpp
	g++ -g -o winattr3 winattr3.cpp -lX11

winattr4: winattr4.cpp
	g++ -g -o winattr4 winattr4.cpp -lX11
