all: 01_fundamentals \
     02_op_arithmetic \
     03_op_relational \
     04_op_true_and_false \
     05_op_logical \
     06_op_conversion \
     07_tips_and_restrictions \
     08_another_example


01_fundamentals: 01_fundamentals.cs Makefile
	mcs 01_fundamentals.cs

02_op_arithmetic: 02_op_arithmetic.cs Makefile
	mcs 02_op_arithmetic.cs

03_op_relational: 03_op_relational.cs Makefile
	mcs 03_op_relational.cs

04_op_true_and_false: 04_op_true_and_false.cs Makefile
	mcs 04_op_true_and_false.cs

05_op_logical: 05_op_logical.cs Makefile
	mcs 05_op_logical.cs

06_op_conversion: 06_op_conversion.cs Makefile
	mcs 06_op_conversion.cs

07_tips_and_restrictions: 07_tips_and_restrictions.cs Makefile
	mcs 07_tips_and_restrictions.cs

08_another_example: 08_another_example.cs Makefile
	mcs 08_another_example.cs


clean:
	rm -v 01_fundamentals.exe \
          02_op_arithmetic.exe \
          03_op_relational.exe \
          04_op_true_and_false.exe \
          05_op_logical.exe \
          06_op_conversion.exe \
          07_tips_and_restrictions.exe \
          08_another_example.exe
