all: 01_overload_fundamentals \
     02_overload_binary_operators \
     03_overload_unary_operators \
     04_operations_on_builtin_types \
     05_overload_relational_operators \
     06_overload_true_and_false \
     07_overload_logical_operators \
     08_short_circuit_operators \
     09_conversion_operator_with_implicit \
     10_conversion_operator_with_explicit \
     11_restrictions \
     12_example_4_bit_type_Nybble


01_overload_fundamentals: 01_overload_fundamentals.cs Makefile
	mcs 01_overload_fundamentals.cs

02_overload_binary_operators: 02_overload_binary_operators.cs Makefile
	mcs 02_overload_binary_operators.cs

03_overload_unary_operators: 03_overload_unary_operators.cs Makefile
	mcs 03_overload_unary_operators.cs

04_operations_on_builtin_types: 04_operations_on_builtin_types.cs Makefile
	mcs 04_operations_on_builtin_types.cs

05_overload_relational_operators: 05_overload_relational_operators.cs Makefile
	mcs 05_overload_relational_operators.cs

06_overload_true_and_false: 06_overload_true_and_false.cs Makefile
	mcs 06_overload_true_and_false.cs

07_overload_logical_operators: 07_overload_logical_operators.cs Makefile
	mcs 07_overload_logical_operators.cs

08_short_circuit_operators: 08_short_circuit_operators.cs Makefile
	mcs 08_short_circuit_operators.cs

09_conversion_operator_with_implicit: 09_conversion_operator_with_implicit.cs Makefile
	mcs 09_conversion_operator_with_implicit.cs

10_conversion_operator_with_explicit: 10_conversion_operator_with_explicit.cs Makefile
	mcs 10_conversion_operator_with_explicit.cs

11_restrictions: 11_restrictions.cs Makefile
	mcs 11_restrictions.cs

12_example_4_bit_type_Nybble: 12_example_4_bit_type_Nybble.cs Makefile
	mcs 12_example_4_bit_type_Nybble.cs


clean:
	rm -v 01_overload_fundamentals.exe \
          02_overload_binary_operators.exe \
          03_overload_unary_operators.exe \
          04_operations_on_builtin_types.exe \
          05_overload_relational_operators.exe \
          06_overload_true_and_false.exe \
          07_overload_logical_operators.exe \
          08_short_circuit_operators.exe \
          09_conversion_operator_with_implicit.exe \
          10_conversion_operator_with_explicit.exe \
          11_restrictions.exe \
          12_example_4_bit_type_Nybble.exe
