all: 01_query \
     02_query_2_times \
     02_where \
     03_where \
     04_orderby \
     05_orderby \
     06_select \
     07_select \
     08_select \
     09_from \
     10_group \
     11_into \
     12_let \
     13_join \
     14_anonymous_type \
     14_group_join \
     15_Select \
     16_GroupBy \
     17_Min \
     18_Average \
     19_Count \
     20_Compile


01_query: 01_query.cs Makefile
	mcs 01_query.cs

02_query_2_times: 02_query_2_times.cs Makefile
	mcs 02_query_2_times.cs

02_where: 02_where.cs Makefile
	mcs 02_where.cs

03_where: 03_where.cs Makefile
	mcs 03_where.cs

04_orderby: 04_orderby.cs Makefile
	mcs 04_orderby.cs

05_orderby: 05_orderby.cs Makefile
	mcs 05_orderby.cs

06_select: 06_select.cs Makefile
	mcs 06_select.cs

07_select: 07_select.cs Makefile
	mcs 07_select.cs

08_select: 08_select.cs Makefile
	mcs 08_select.cs

09_from: 09_from.cs Makefile
	mcs 09_from.cs

10_group: 10_group.cs Makefile
	mcs 10_group.cs

11_into: 11_into.cs Makefile
	mcs 11_into.cs

12_let: 12_let.cs Makefile
	mcs 12_let.cs

13_join: 13_join.cs Makefile
	mcs 13_join.cs

14_anonymous_type: 14_anonymous_type.cs Makefile
	mcs 14_anonymous_type.cs

14_group_join: 14_group_join.cs Makefile
	mcs 14_group_join.cs

15_Select: 15_Select.cs Makefile
	mcs 15_Select.cs

16_GroupBy: 16_GroupBy.cs Makefile
	mcs 16_GroupBy.cs

17_Min: 17_Min.cs Makefile
	mcs 17_Min.cs

18_Average: 18_Average.cs Makefile
	mcs 18_Average.cs

19_Count: 19_Count.cs Makefile
	mcs 19_Count.cs

20_Compile: 20_Compile.cs Makefile
	mcs 20_Compile.cs



clean:
	rm -v 01_query.exe \
          02_query_2_times.exe \
          02_where.exe \
          03_where.exe \
          04_orderby.exe \
          05_orderby.exe \
          06_select.exe \
          07_select.exe \
          08_select.exe \
          09_from.exe \
          10_group.exe \
          11_into.exe \
          12_let.exe \
          13_join.exe \
          14_anonymous_type.exe \
          14_group_join.exe \
          15_Select.exe \
          16_GroupBy.exe \
          17_Min.exe \
          18_Average.exe \
          19_Count.exe \
          20_Compile.exe
