all: 01_basics \
     02_member_access \
     03_name_hidding \
     04_multilevel_hierarchy \
     05_when_are_ctors_called \
     06_derived_objects \
     07_virtual_methods \
     08_abstract_classes \
     09_sealed_prevent_inheritance \
     10_the_object_class



01_basics: 01_basics.cs Makefile
	mcs 01_basics.cs

02_member_access: 02_member_access.cs Makefile
	mcs 02_member_access.cs

03_name_hidding: 03_name_hidding.cs Makefile
	mcs 03_name_hidding.cs

04_multilevel_hierarchy: 04_multilevel_hierarchy.cs Makefile
	mcs 04_multilevel_hierarchy.cs

05_when_are_ctors_called: 05_when_are_ctors_called.cs Makefile
	mcs 05_when_are_ctors_called.cs

06_derived_objects: 06_derived_objects.cs Makefile
	mcs 06_derived_objects.cs

07_virtual_methods: 07_virtual_methods.cs Makefile
	mcs 07_virtual_methods.cs

08_abstract_classes: 08_abstract_classes.cs Makefile
	mcs 08_abstract_classes.cs

09_sealed_prevent_inheritance: 09_sealed_prevent_inheritance.cs Makefile
	mcs 09_sealed_prevent_inheritance.cs

10_the_object_class: 10_the_object_class.cs Makefile
	mcs 10_the_object_class.cs


clean:
	rm -v 01_basics.exe \
          02_member_access.exe \
          03_name_hidding.exe \
          04_multilevel_hierarchy.exe \
          05_when_are_ctors_called.exe \
          06_derived_objects.exe \
          07_virtual_methods.exe \
          08_abstract_classes.exe \
          09_sealed_prevent_inheritance.exe \
          10_the_object_class.exe
