all:  01_arithmetic_operators \
      02_relational_operators \
      03_logical_operators \
      04_implication_idiom \
      05_short_circuit_idiom \
      06_assignament_operator \
      07_bitwise_operators \
      08_shift_operators \
      09_question_mark_operator \
      10_spaces_and_paranthesis \
      11_operator_precedence

01_arithmetic_operators: 01_arithmetic_operators.cs Makefile
	mcs 01_arithmetic_operators.cs

02_relational_operators: 02_relational_operators.cs Makefile
	mcs 02_relational_operators.cs

03_logical_operators: 03_logical_operators.cs Makefile
	mcs 03_logical_operators.cs

04_implication_idiom: 04_implication_idiom.cs Makefile
	mcs 04_implication_idiom.cs

05_short_circuit_idiom: 05_short_circuit_idiom.cs Makefile
	mcs 05_short_circuit_idiom.cs

06_assignament_operator: 06_assignament_operator.cs Makefile
	mcs 06_assignament_operator.cs

07_bitwise_operators: 07_bitwise_operators.cs Makefile
	mcs 07_bitwise_operators.cs

08_shift_operators: 08_shift_operators.cs Makefile
	mcs 08_shift_operators.cs

09_question_mark_operator: 09_question_mark_operator.cs Makefile
	mcs 09_question_mark_operator.cs

10_spaces_and_paranthesis: 10_spaces_and_paranthesis.cs Makefile
	mcs 10_spaces_and_paranthesis.cs

11_operator_precedence: 11_operator_precedence.cs Makefile
	mcs 11_operator_precedence.cs


clean:
	rm -v 01_arithmetic_operators.exe \
          02_relational_operators.exe \
          03_logical_operators.exe \
          04_implication_idiom.exe \
          05_short_circuit_idiom.exe \
          06_assignament_operator.exe \
          07_bitwise_operators.exe \
          08_shift_operators.exe \
          09_question_mark_operator.exe \
          10_spaces_and_paranthesis.exe \
          11_operator_precedence.exe
