all: 01_access_a_website \
     02_handle_network_exceptions \
     03_use_uri \
     04_examine_the_headers \
     05_examine_the_cookies \
     06_www_last_modified \
     07_web_crawler \
     08_download_to_file


01_access_a_website: 01_access_a_website.cs Makefile
	mcs 01_access_a_website.cs

02_handle_network_exceptions: 02_handle_network_exceptions.cs Makefile
	mcs 02_handle_network_exceptions.cs

03_use_uri: 03_use_uri.cs Makefile
	mcs 03_use_uri.cs

04_examine_the_headers: 04_examine_the_headers.cs Makefile
	mcs 04_examine_the_headers.cs

05_examine_the_cookies: 05_examine_the_cookies.cs Makefile
	mcs 05_examine_the_cookies.cs

06_www_last_modified: 06_www_last_modified.cs Makefile
	mcs 06_www_last_modified.cs

07_web_crawler: 07_web_crawler.cs Makefile
	mcs 07_web_crawler.cs

08_download_to_file: 08_download_to_file.cs Makefile
	mcs 08_download_to_file.cs


clean:
	rm -v 01_access_a_website.exe \
          02_handle_network_exceptions.exe \
          03_use_uri.exe \
          04_examine_the_headers.exe \
          05_examine_the_cookies.exe \
          06_www_last_modified.exe \
          07_web_crawler.exe \
          08_download_to_file.exe
