all: clr1

clr1: clr1.cpp
	g++ -g -o clr1 clr1.cpp -lX11

clr2: clr2.cpp
	g++ -g -o clr2 clr2.cpp -lX11

clr3: clr3.cpp
	g++ -g -o clr3 clr3.cpp -lX11

clr4: clr4.cpp
	g++ -g -o clr4 clr4.cpp -lX11

clr5: clr5.cpp
	g++ -g -o clr5 clr5.cpp -lX11

clr6: clr6.cpp
	g++ -g -o clr6 clr6.cpp -lX11

clr7: clr7.cpp
	g++ -g -o clr7 clr7.cpp -lX11

clr8: clr8.cpp
	g++ -g -o clr8 clr8.cpp -lX11




clean:
	rm clr{1,2,3,4,5,6,7,8,9} \
       clr1{0,1,2,3,4,5,6,7,8,9}
