all: 01_arrays \
     02_multidimensional_arrays \
     03_jagged_arrays \
     04_array_references \
     05_property_length \
     06_implicit_type_of \
     07_foreach \
     08_strings


01_arrays: 01_arrays.cs Makefile
	mcs 01_arrays.cs

02_multidimensional_arrays: 02_multidimensional_arrays.cs Makefile
	mcs 02_multidimensional_arrays.cs

03_jagged_arrays: 03_jagged_arrays.cs Makefile
	mcs 03_jagged_arrays.cs

04_array_references: 04_array_references.cs Makefile
	mcs 04_array_references.cs

05_property_length: 05_property_length.cs Makefile
	mcs 05_property_length.cs

06_implicit_type_of: 06_implicit_type_of.cs Makefile
	mcs 06_implicit_type_of.cs

07_foreach: 07_foreach.cs Makefile
	mcs 07_foreach.cs

08_strings: 08_strings.cs Makefile
	mcs 08_strings.cs


clean:
	rm -v  01_arrays.exe \
           02_multidimensional_arrays.exe \
           03_jagged_arrays.exe \
           04_array_references.exe \
           05_property_length.exe \
           06_implicit_type_of.exe \
           07_foreach.exe \
           08_strings.exe
