all: simple5

basicwin:
	g++ -g -o basicwin basicwin.cpp -lX11

simple1:
	g++ -g -o simple1 simple1.cpp -lX11

simple2:
	g++ -g -o simple2 simple2.cpp -lX11

simple3:
	g++ -g -o simple3 simple3.cpp -lX11

simple4:
	g++ -g -o simple4 simple4.cpp -lX11

simple5:
	g++ -g -o simple5 simple5.cpp -lX11

clean:
	rm basicwin simple1 simple2 simple3 \
       simple4 simple5
