all: 01_delegates \
     02_anonymous_functions \
     03_anonymous_methods \
     04_lambdas \
     05_events \
     06_example \
     07_event_guidelines \
     08_applying_events


01_delegates: 01_delegates.cs Makefile
	mcs 01_delegates.cs

02_anonymous_functions: 02_anonymous_functions.cs Makefile
	mcs 02_anonymous_functions.cs

03_anonymous_methods: 03_anonymous_methods.cs Makefile
	mcs 03_anonymous_methods.cs

04_lambdas: 04_lambdas.cs Makefile
	mcs 04_lambdas.cs

05_events: 05_events.cs Makefile
	mcs 05_events.cs

06_example: 06_example.cs Makefile
	mcs 06_example.cs

07_event_guidelines: 07_event_guidelines.cs Makefile
	mcs 07_event_guidelines.cs

08_applying_events: 08_applying_events.cs Makefile
	mcs 08_applying_events.cs


clean:
	rm -v 01_delegates.exe \
          02_anonymous_functions.exe \
          03_anonymous_methods.exe \
          04_lambdas.exe \
          05_events.exe \
          06_example.exe \
          07_event_guidelines.exe \
          08_applying_events.exe
