all: 01_delegate_using_new \
     02_delegate_to_static \
     03_delegate_to_method \
     04_delegate_multicast \
     05_covariance \
     06_anonymous_method \
     07_anonymous_method_params \
     08_anonymous_method_return \
     09_anonymous_methods_variables \
     10_lambda_expression \
     11_lambda_statement \
     12_lambda_statement \
     13_event \
     14_event_multicast \
     15_event_handler_method \
     16_event_handler_static \
     17_event_handler_lambda \
     18_event_accessor \
     19_event_dotnet_guideline \
     20_builtin_EventHandler \
     21_a_keypress_sample


01_delegate_using_new: 01_delegate_using_new.cs Makefile
	mcs 01_delegate_using_new.cs

02_delegate_to_static: 02_delegate_to_static.cs Makefile
	mcs 02_delegate_to_static.cs

03_delegate_to_method: 03_delegate_to_method.cs Makefile
	mcs 03_delegate_to_method.cs

04_delegate_multicast: 04_delegate_multicast.cs Makefile
	mcs 04_delegate_multicast.cs

05_covariance: 05_covariance.cs Makefile
	mcs 05_covariance.cs

06_anonymous_method: 06_anonymous_method.cs Makefile
	mcs 06_anonymous_method.cs

07_anonymous_method_params: 07_anonymous_method_params.cs Makefile
	mcs 07_anonymous_method_params.cs

08_anonymous_method_return: 08_anonymous_method_return.cs Makefile
	mcs 08_anonymous_method_return.cs

09_anonymous_methods_variables: 09_anonymous_methods_variables.cs Makefile
	mcs 09_anonymous_methods_variables.cs

10_lambda_expression: 10_lambda_expression.cs Makefile
	mcs 10_lambda_expression.cs

11_lambda_statement: 11_lambda_statement.cs Makefile
	mcs 11_lambda_statement.cs

12_lambda_statement: 12_lambda_statement.cs Makefile
	mcs 12_lambda_statement.cs

13_event: 13_event.cs Makefile
	mcs 13_event.cs

14_event_multicast: 14_event_multicast.cs Makefile
	mcs 14_event_multicast.cs

15_event_handler_method: 15_event_handler_method.cs Makefile
	mcs 15_event_handler_method.cs

16_event_handler_static: 16_event_handler_static.cs Makefile
	mcs 16_event_handler_static.cs

17_event_handler_lambda: 17_event_handler_lambda.cs Makefile
	mcs 17_event_handler_lambda.cs

18_event_accessor: 18_event_accessor.cs Makefile
	mcs 18_event_accessor.cs

19_event_dotnet_guideline: 19_event_dotnet_guideline.cs Makefile
	mcs 19_event_dotnet_guideline.cs

20_builtin_EventHandler: 20_builtin_EventHandler.cs Makefile
	mcs 20_builtin_EventHandler.cs

21_a_keypress_sample: 21_a_keypress_sample.cs Makefile
	mcs 21_a_keypress_sample.cs


clean:
	rm -v 01_delegate_using_new.exe \
          02_delegate_to_static.exe \
          03_delegate_to_method.exe \
          04_delegate_multicast.exe \
          05_covariance.exe \
          06_anonymous_method.exe \
          07_anonymous_method_params.exe \
          08_anonymous_method_return.exe \
          09_anonymous_methods_variables.exe \
          10_lambda_expression.exe \
          11_lambda_statement.exe \
          12_lambda_statement.exe \
          13_event.exe \
          14_event_multicast.exe \
          15_event_handler_method.exe \
          16_event_handler_static.exe \
          17_event_handler_lambda.exe \
          18_event_accessor.exe \
          19_event_dotnet_guideline.exe \
          20_builtin_EventHandler.exe \
          21_a_keypress_sample.exe
