all: 01_ArrayList \
     02_ArrayList.Sort \
     03_ArrayList.ToArray \
     04_Hashtable \
     05_SortedList \
     06_Stack \
     07_Queue \
     08_Bitarray \
     09_List \
     10_LinkedList \
     11_Dictionary \
     12_SortedDictionary \
     13_SortedList \
     14_Stack \
     15_Queue \
     16_HashSet \
     17_BlockingCollection \
     18_BlockingCollection.TryTake \
     19_a_simple_inventory \
     20_a_type_safe_inventory \
     21_non_generic_IComparable \
     22_generic_IComparable \
     23_non_generic_IComparer \
     24_generic_IComparer \
     25_collection_as_Enumerator \
     26_collection_as_IDictionaryEnumerator \
     27_non_generic_IEnumerable \
     28_yield_iterator \
     29_yield_dynamic \
     30_yield_break \
     31_yield_n_times \
     32_yield_with_a_name \
     33_yield_generic



01_ArrayList: 01_ArrayList.cs Makefile
	mcs 01_ArrayList.cs

02_ArrayList.Sort: 02_ArrayList.Sort.cs Makefile
	mcs 02_ArrayList.Sort.cs

03_ArrayList.ToArray: 03_ArrayList.ToArray.cs Makefile
	mcs 03_ArrayList.ToArray.cs

04_Hashtable: 04_Hashtable.cs Makefile
	mcs 04_Hashtable.cs

05_SortedList: 05_SortedList.cs Makefile
	mcs 05_SortedList.cs

06_Stack: 06_Stack.cs Makefile
	mcs 06_Stack.cs

07_Queue: 07_Queue.cs Makefile
	mcs 07_Queue.cs

08_Bitarray: 08_Bitarray.cs Makefile
	mcs 08_Bitarray.cs

09_List: 09_List.cs Makefile
	mcs 09_List.cs

10_LinkedList: 10_LinkedList.cs Makefile
	mcs 10_LinkedList.cs

11_Dictionary: 11_Dictionary.cs Makefile
	mcs 11_Dictionary.cs

12_SortedDictionary: 12_SortedDictionary.cs Makefile
	mcs 12_SortedDictionary.cs

13_SortedList: 13_SortedList.cs Makefile
	mcs 13_SortedList.cs

14_Stack: 14_Stack.cs Makefile
	mcs 14_Stack.cs

15_Queue: 15_Queue.cs Makefile
	mcs 15_Queue.cs

16_HashSet: 16_HashSet.cs Makefile
	mcs 16_HashSet.cs

17_BlockingCollection: 17_BlockingCollection.cs Makefile
	mcs 17_BlockingCollection.cs

18_BlockingCollection.TryTake: 18_BlockingCollection.TryTake.cs Makefile
	mcs 18_BlockingCollection.TryTake.cs

19_a_simple_inventory: 19_a_simple_inventory.cs Makefile
	mcs 19_a_simple_inventory.cs

20_a_type_safe_inventory: 20_a_type_safe_inventory.cs Makefile
	mcs 20_a_type_safe_inventory.cs

21_non_generic_IComparable: 21_non_generic_IComparable.cs Makefile
	mcs 21_non_generic_IComparable.cs

22_generic_IComparable: 22_generic_IComparable.cs Makefile
	mcs 22_generic_IComparable.cs

23_non_generic_IComparer: 23_non_generic_IComparer.cs Makefile
	mcs 23_non_generic_IComparer.cs

24_generic_IComparer: 24_generic_IComparer.cs Makefile
	mcs 24_generic_IComparer.cs

25_collection_as_Enumerator: 25_collection_as_Enumerator.cs Makefile
	mcs 25_collection_as_Enumerator.cs

26_collection_as_IDictionaryEnumerator: 26_collection_as_IDictionaryEnumerator.cs Makefile
	mcs 26_collection_as_IDictionaryEnumerator.cs

27_non_generic_IEnumerable: 27_non_generic_IEnumerable.cs Makefile
	mcs 27_non_generic_IEnumerable.cs

28_yield_iterator: 28_yield_iterator.cs Makefile
	mcs 28_yield_iterator.cs

29_yield_dynamic: 29_yield_dynamic.cs Makefile
	mcs 29_yield_dynamic.cs

30_yield_break: 30_yield_break.cs Makefile
	mcs 30_yield_break.cs

31_yield_n_times: 31_yield_n_times.cs Makefile
	mcs 31_yield_n_times.cs

32_yield_with_a_name: 32_yield_with_a_name.cs Makefile
	mcs 32_yield_with_a_name.cs

33_yield_generic: 33_yield_generic.cs Makefile
	mcs 33_yield_generic.cs


clean:
	rm -v 01_ArrayList.exe \
          02_ArrayList.Sort.exe \
          03_ArrayList.ToArray.exe \
          04_Hashtable.exe \
          05_SortedList.exe \
          06_Stack.exe \
          07_Queue.exe \
          08_Bitarray.exe \
          09_List.exe \
          10_LinkedList.exe \
          11_Dictionary.exe \
          12_SortedDictionary.exe \
          13_SortedList.exe \
          14_Stack.exe \
          15_Queue.exe \
          16_HashSet.exe \
          17_BlockingCollection.exe \
          18_BlockingCollection.TryTake.exe \
          19_a_simple_inventory.exe \
          20_a_type_safe_inventory.exe \
          21_non_generic_IComparable.exe \
          22_generic_IComparable.exe \
          23_non_generic_IComparer.exe \
          24_generic_IComparer.exe \
          25_collection_as_Enumerator.exe \
          26_collection_as_IDictionaryEnumerator.exe \
          27_non_generic_IEnumerable.exe \
          28_yield_iterator.exe \
          29_yield_dynamic.exe \
          30_yield_break.exe \
          31_yield_n_times.exe \
          32_yield_with_a_name.exe \
          33_yield_generic.exe
