all: cad

sources = 
objects = 

cad:
#cad: $(sources)
#	g++ -c $(sources)
#	ar  rcs libcad.a $(objects)

#	g++ -c -fPIC $(sources)
#	g++ -shared -Wl,-soname,libcad.so.1 -o libcad.so.1.0.1 $(objects)

clean:
	rm *.o libcad.a libcad.so.1.0.1