all clean:
	cd ./Adapter && $(MAKE) $@
	cd ./Bridge && $(MAKE) $@
	cd ./Builder && $(MAKE) $@
	cd ./ChainOfResponsibility && $(MAKE) $@
	cd ./Command && $(MAKE) $@
	cd ./Composite && $(MAKE) $@
	cd ./Compound && $(MAKE) $@
	cd ./Decorator && $(MAKE) $@
	cd ./Facade && $(MAKE) $@
	cd ./Factory && $(MAKE) $@
	cd ./Flyweight && $
	cd ./Interpreter && $(MAKE) $@
	cd ./Iterator && $(MAKE) $@
	cd ./Mediator && $(MAKE) $@
	cd ./Observer && $(MAKE) $@
	cd ./Singleton && $(MAKE) $@
	cd ./State && $(MAKE) $@
	cd ./Strategy && $(MAKE) $@
	cd ./Template && $(MAKE) $@
	cd ./Visitor && $(MAKE) $@
