all: key1

key1: key1.cpp
	g++ -g -o key1 key1.cpp -lX11

key2: key2.cpp
	g++ -g -o key2 key2.cpp -lX11

key3: key3.cpp
	g++ -g -o key3 key3.cpp -lX11

ms1: ms1.cpp
	g++ -g -o ms1 ms1.cpp -lX11

ms2: ms2.cpp
	g++ -g -o ms2 ms2.cpp -lX11


clean:
	rm -v  key{1,2,3,4,5,6,7,8,9} \
           key1{0,1,2,3,4,5,6,7,8,9} \
           ms{1,2,3,4,5,6,7,8,9} \
           ms1{0,1,2,3,4,5,6,7,8,9}
