all: 01_generics \
     02_non_generics \
     03_generics_2T \
     04_constrained_types \
     05_phone_list_sample \
     06_constrained_interface \
     07_constrained_new \
     08_constrained_reference \
     09_constrained_type \
     10_constrained_relationship \
     11_constrained_multiple \
     12_generics_default \
     13_generics_structures \
     14_generics_method \
     15_generics_delegates \
     16_generics_interfaces \
     17_generics_compare \
     18_generics_hierarchies \
     19_generics_base_sample \
     20_generics_derived_sample \
     21_generics_overriding_method \
     22_generics_overriding_ambiguity \
     23_generics_covariance \
     24_generics_contravariance \
     25_generics_delegate_covariance


01_generics: 01_generics.cs Makefile
	mcs 01_generics.cs

02_non_generics: 02_non_generics.cs Makefile
	mcs 02_non_generics.cs

03_generics_2T: 03_generics_2T.cs Makefile
	mcs 03_generics_2T.cs

04_constrained_types: 04_constrained_types.cs Makefile
	mcs 04_constrained_types.cs

05_phone_list_sample: 05_phone_list_sample.cs Makfile
	mcs 05_phone_list_sample.cs

06_constrained_interface: 06_constrained_interface.cs Makefile
	mcs 06_constrained_interface.cs

07_constrained_new: 07_constrained_new.cs Makefile
	mcs 07_constrained_new.cs

08_constrained_reference: 08_constrained_reference.cs Makefile
	mcs 08_constrained_reference.cs

09_constrained_type: 09_constrained_type.cs Makefile
	mcs 09_constrained_type.cs

10_constrained_relationship: 10_constrained_relationship.cs Makefile
	mcs 10_constrained_relationship.cs

11_constrained_multiple: 11_constrained_multiple.cs Makefile
	mcs 11_constrained_multiple.cs

12_generics_default: 12_generics_default.cs Makefile
	mcs 12_generics_default.cs

13_generics_structures: 13_generics_structures.cs Makefile
	mcs 13_generics_structures.cs

14_generics_method: 14_generics_method.cs Makefile
	mcs 14_generics_method.cs

15_generics_delegates: 15_generics_delegates.cs Makefile
	mcs 15_generics_delegates.cs

16_generics_interfaces: 16_generics_interfaces.cs Makefile
	mcs 16_generics_interfaces.cs

17_generics_compare: 17_generics_compare.cs Makefile
	mcs 17_generics_compare.cs

18_generics_hierarchies: 18_generics_hierarchies.cs Makefile
	mcs 18_generics_hierarchies.cs

19_generics_base_sample: 19_generics_base_sample.cs Makefile
	mcs 19_generics_base_sample.cs

20_generics_derived_sample: 20_generics_derived_sample.cs Makefile
	mcs 20_generics_derived_sample.cs

21_generics_overriding_method: 21_generics_overriding_method.cs Makefile
	mcs 21_generics_overriding_method.cs

22_generics_overriding_ambiguity: 22_generics_overriding_ambiguity.cs Makefile
	mcs 22_generics_overriding_ambiguity.cs

23_generics_covariance: 23_generics_covariance.cs Makefile
	mcs 23_generics_covariance.cs

24_generics_contravariance: 24_generics_contravariance.cs Makefile
	mcs 24_generics_contravariance.cs

25_generics_delegate_covariance: 25_generics_delegate_covariance.cs Makefile
	mcs 25_generics_delegate_covariance.cs


clean:
	rm -v 01_generics.exe \
          02_non_generics.exe \
          03_generics_2T.exe \
          04_constrained_types.exe \
          05_phone_list_sample.exe \
          06_constrained_interface.exe \
          07_constrained_new.exe \
          08_constrained_reference.exe \
          09_constrained_type.exe \
          10_constrained_relationship.exe \
          11_constrained_multiple.exe \
          12_generics_default.exe \
          13_generics_structures.exe \
          14_generics_method.exe \
          15_generics_delegates.exe \
          16_generics_interfaces.exe \
          17_generics_compare.exe \
          18_generics_hierarchies.exe \
          19_generics_base_sample.exe \
          20_generics_derived_sample.exe \
          21_generics_overriding_method.exe \
          22_generics_overriding_ambiguity.exe \
          23_generics_covariance.exe \
          24_generics_contravariance.exe \
          25_generics_delegate_covariance.exe
