all: draw1

draw1: draw1.cpp
	g++ -g -o draw1 draw1.cpp -lX11

draw2: draw2.cpp
	g++ -g -o draw2 draw2.cpp -lX11

draw3: draw3.cpp
	g++ -g -o draw3 draw3.cpp -lX11

draw4: draw4.cpp
	g++ -g -o draw4 draw4.cpp -lX11

draw5: draw5.cpp
	g++ -g -o draw5 draw5.cpp -lX11

draw6: draw6.cpp
	g++ -g -o draw6 draw6.cpp -lX11


clean:
	rm -v draw{1,2,3,4,5,6,7,8,9} \
          draw1{0,1,2,3,4,5,6,7,8,9}
