# .bashrc
# cp $HOME/.bashrc  $HOME/Code/git-main/script/bash/bashrc
# git status $HOME/Code/git-main


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
# If not running interactively, don't do anything
[[ $- != *i* ]] && return



if [ -f $HOME/.bash_aliases ]; then
	. $HOME/.bash_aliases
fi

if [ -f $HOME/.bash_i3 ]; then
	. $HOME/.bash_i3
fi

if [ -f $HOME/.bash_gpg ]; then
	. $HOME/.bash_gpg
fi

if [ -f $HOME/.bash_iptables ]; then
	. $HOME/.bash_iptables
fi
