all: 01_controlling_access \
     02_references_to_methods \
     03_ref_and_out \
     04_variable_no_of_args \
     05_return_objects \
     06_method_overloading \
     07_ctor_overloading \
     08_object_initializers \
     09_optional_args \
     10_named_args \
     11_the_Main \
     12_recursion \
     13_static \
     14_static_classes


01_controlling_access: 01_controlling_access.cs Makefile
	mcs 01_controlling_access.cs

02_references_to_methods: 02_references_to_methods.cs Makefile
	mcs 02_references_to_methods.cs

03_ref_and_out: 03_ref_and_out.cs Makefile
	mcs 03_ref_and_out.cs

04_variable_no_of_args: 04_variable_no_of_args.cs Makefile
	mcs 04_variable_no_of_args.cs

05_return_objects: 05_return_objects.cs Makefile
	mcs 05_return_objects.cs

06_method_overloading: 06_method_overloading.cs Makefile
	mcs 06_method_overloading.cs

07_ctor_overloading: 07_ctor_overloading.cs Makefile
	mcs 07_ctor_overloading.cs

08_object_initializers: 08_object_initializers.cs Makefile
	mcs 08_object_initializers.cs

09_optional_args: 09_optional_args.cs Makefile
	mcs 09_optional_args.cs

10_named_args: 10_named_args.cs Makefile
	mcs 10_named_args.cs

11_the_Main: 11_the_Main.cs Makefile
	mcs 11_the_Main.cs

12_recursion: 12_recursion.cs Makefile
	mcs 12_recursion.cs

13_static: 13_static.cs Makefile
	mcs 13_static.cs

14_static_classes: 14_static_classes.cs Makefile
	mcs 14_static_classes.cs


clean:
	rm -v 01_controlling_access.exe \
          02_references_to_methods.exe
          03_ref_and_out.exe
          04_variable_no_of_args.exe
          05_return_objects.exe
          06_method_overloading.exe
          07_ctor_overloading.exe
          08_object_initializers.exe
          09_optional_args.exe
          10_named_args.exe
          11_the_Main.exe
          12_recursion.exe
          13_static.exe
          14_static_classes.exe
