all:  01_controlling_access \
      02_controlling_access_stackex \
      03_references_to_methods \
      04_pass_type_by_value \
      05_pass_object_by_reference \
      06_pass_value_with_ref \
      07_pass_value_with_ref \
      08_pass_value_with_out \
      09_pass_value_with_out \
      10_pass_object_with_ref \
      11_variable_no_of_args \
      12_variable_no_of_args \
      13_return_an_object \
      14_a_class_factory \
      15_return_an_array \
      16_method_overloading \
      17_implicit_type_conversion \
      18_exact_type_match \
      19_ctor_overloading \
      20_ctor_overloading_stackex \
      21_call_ctor_with_this \
      22_object_initializers \
      23_optional_args \
      24_ambiguity \
      25_simplify_a_call \
      26_named_args \
      27_void_Main \
      28_int_Main \
      29_void_Main_args \
      30_int_Main_args \
      31_recursion \
      32_reverse_using_recursion \
      33_static_keyword \
      34_static_illegal \
      35_use_of_static_member \
      36_static_class_factory \
      37_static_ctors \
      38_static_classes


01_controlling_access: 01_controlling_access.cs Makefile
	mcs 01_controlling_access.cs

02_controlling_access_stackex: 02_controlling_access_stackex.cs Makefile
	mcs 01_controlling_access.cs

03_references_to_methods: 03_references_to_methods.cs Makefile
	mcs 03_references_to_methods.cs

04_pass_type_by_value: 04_pass_type_by_value.cs Makefile
	mcs 04_pass_type_by_value.cs

05_pass_object_by_reference: 05_pass_object_by_reference.cs Makefile
	mcs 05_pass_object_by_reference.cs

06_pass_value_with_ref: 06_pass_value_with_ref.cs Makefile
	mcs 06_pass_value_with_ref.cs

07_pass_value_with_ref: 07_pass_value_with_ref.cs Makefile
	mcs 07_pass_value_with_ref.cs

08_pass_value_with_out: 08_pass_value_with_out.cs Makefile
	mcs 08_pass_value_with_out.cs

09_pass_value_with_out: 09_pass_value_with_out.cs Makefile
	mcs 08_pass_value_with_out.cs

10_pass_object_with_ref: 10_pass_object_with_ref.cs Makefile
	mcs 10_pass_object_with_ref.cs

11_variable_no_of_args: 11_variable_no_of_args.cs Makefile
	mcs 11_variable_no_of_args.cs

12_variable_no_of_args: 12_variable_no_of_args.cs Makefile
	mcs 12_variable_no_of_args.cs

13_return_an_object: 13_return_an_object.cs Makefile
	mcs 13_return_an_object.cs

14_a_class_factory: 14_a_class_factory.cs Makefile
	mcs 14_a_class_factory.cs

15_return_an_array: 15_return_an_array.cs Makefile
	mcs 15_return_an_array.cs

16_method_overloading: 16_method_overloading.cs Makefile
	mcs 16_method_overloading.cs

17_implicit_type_conversion: 17_implicit_type_conversion.cs Makefile
	mcs 17_implicit_type_conversion.cs

18_exact_type_match: 18_exact_type_match.cs Makefile
	mcs 18_exact_type_match.cs

19_ctor_overloading: 19_ctor_overloading.cs Makefile
	mcs 19_ctor_overloading.cs

20_ctor_overloading_stackex: 20_ctor_overloading_stackex.cs Makefile
	mcs 20_ctor_overloading_stackex.cs

21_call_ctor_with_this: 21_call_ctor_with_this.cs Makefile
	mcs 21_call_ctor_with_this.cs

22_object_initializers: 22_object_initializers.cs Makefile
	mcs 22_object_initializers.cs

23_optional_args: 23_optional_args.cs Makefile
	mcs 23_optional_args.cs

24_ambiguity: 24_ambiguity.cs Makefile
	mcs 24_ambiguity.cs

25_simplify_a_call: 25_simplify_a_call.cs Makefile
	mcs 25_simplify_a_call.cs

26_named_args: 26_named_args.cs Makefile
	mcs 26_named_args.cs

27_void_Main: 27_void_Main.cs Makefile
	mcs 27_void_Main.cs

28_int_Main: 28_int_Main.cs Makefile
	mcs 28_int_Main.cs

29_void_Main_args: 29_void_Main_args.cs Makefile
	mcs 29_void_Main_args.cs

30_int_Main_args: 30_int_Main_args.cs Makefile
	mcs 30_int_Main_args.cs

31_recursion: 31_recursion.cs Makefile
	mcs 31_recursion.cs

32_reverse_using_recursion: 32_reverse_using_recursion.cs Makefile
	mcs 32_reverse_using_recursion.cs

33_static_keyword: 33_static_keyword.cs Makefile
	mcs 33_static_keyword.cs

34_static_illegal: 34_static_illegal.cs Makefile
	mcs 34_static_illegal.cs

35_use_of_static_member: 35_use_of_static_member.cs Makefile
	mcs 35_use_of_static_member.cs

36_static_class_factory: 36_static_class_factory.cs Makefile
	mcs 36_static_class_factory.cs

37_static_ctors: 37_static_ctors.cs Makefile
	mcs 37_static_ctors.cs

38_static_classes: 38_static_classes.cs Makefile
	#mcs 38_static_classes.cs
	echo "38_static_classes.cs error"



clean:
	rm -v 01_controlling_access.exe \
          02_controlling_access_stackex.exe \
          03_references_to_methods.exe \
          04_pass_type_by_value.exe \
          05_pass_object_by_reference.exe \
          06_pass_value_with_ref.exe \
          07_pass_value_with_ref.exe \
          08_pass_value_with_out.exe \
          09_pass_value_with_out.exe \
          10_pass_object_with_ref.exe \
          11_variable_no_of_args.exe \
          12_variable_no_of_args.exe \
          13_return_an_object.exe \
          14_a_class_factory.exe \
          15_return_an_array.exe \
          16_method_overloading.exe \
          17_implicit_type_conversion.exe \
          18_exact_type_match.exe \
          19_ctor_overloading.exe \
          20_ctor_overloading_stackex.exe \
          21_call_ctor_with_this.exe \
          22_object_initializers.exe \
          23_optional_args.exe \
          24_ambiguity.exe \
          25_simplify_a_call.exe \
          26_named_args.exe \
          27_void_Main.exe \
          28_int_Main.exe \
          29_void_Main_args.exe \
          30_int_Main_args.exe \
          31_recursion.exe \
          32_reverse_using_recursion.exe \
          33_static_keyword.exe \
          34_static_illegal.exe \
          35_use_of_static_member.exe \
          36_static_class_factory.exe \
          37_static_ctors.exe \
          38_static_classes.exe
