all: 01_value_types \
     02_integers \
     03_long \
     04_byte \
     05_float \
     06_double \
     07_decimal \
     08_char \
     09_bool \
     10_string_formatting \
     11_hexadecimal_literals \
     12_escape_literals \
     13_string_literals \
     14_variables \
     15_var_type \
     16_scope_block \
     17_scope_illegal \
     18_type_conversion_assignament \
     19_casting_incompatible_types \
     20_type_conversion_expression

01_value_types: 01_value_types.cs Makefile
	mcs 01_value_types.cs

02_integers: 02_integers.cs Makefile
	mcs 02_integers.cs

03_long: 03_long.cs Makefile
	mcs 03_long.cs

04_byte: 04_byte.cs Makefile
	mcs 04_byte.cs

05_float: 05_float.cs Makefile
	mcs 05_float.cs

06_double: 06_double.cs Makefile
	mcs 06_double.cs

07_decimal: 07_decimal.cs Makefile
	mcs 07_decimal.cs

08_char: 08_char.cs Makefile
	mcs 08_char.cs

09_bool: 09_bool.cs Makefile
	mcs 09_bool.cs

10_string_formatting: 10_string_formatting.cs Makefile
	mcs 10_string_formatting.cs

11_hexadecimal_literals: 11_hexadecimal_literals.cs Makefile
	mcs 11_hexadecimal_literals.cs

12_escape_literals: 12_escape_literals.cs Makefile
	mcs 12_escape_literals.cs

13_string_literals: 13_string_literals.cs Makefile
	mcs 13_string_literals.cs

14_variables: 14_variables.cs Makefile
	mcs 14_variables.cs

15_var_type: 15_var_type.cs Makefile
	mcs 15_var_type.cs

16_scope_block: 16_scope_block.cs Makefile
	mcs 16_scope_block.cs

17_scope_illegal: 17_scope_illegal.cs Makefile
	mcs 17_scope_illegal.cs

18_type_conversion_assignament: 18_type_conversion_assignament.cs Makefile
	mcs 18_type_conversion_assignament.cs

19_casting_incompatible_types: 19_casting_incompatible_types.cs Makefile
	mcs 19_casting_incompatible_types.cs

20_type_conversion_expression: 20_type_conversion_expression.cs Makefile
	mcs 20_type_conversion_expression.cs


clean:
	rm -v  01_value_types \
           02_integers \
           03_long \
           04_byte \
           05_float \
           06_double \
           07_decimal \
           08_char \
           09_bool \
           10_string_formatting \
           11_hexadecimal_literals \
           12_escape_literals \
           13_string_literals \
           14_variables \
           15_var_type \
           16_scope_block \
           17_scope_illegal \
           18_type_conversion_assignament \
           19_casting_incompatible_types \
           20_type_conversion_expression
