/*  Cap.7   Queries
    7.6     LIMIT and OFFET

    psql -d mytestdb -U pgmihai
    \i 16 limit_and_offset.sql
    \?
    \qecho '\033[2J'
*/


/*      LIMIT and OFFSET allow you to retrieve just a portion of the rows
        that are generated by the rest of the query:

        SELECT sel_list
               FROM table_expr
               [ORDER BY ...]
               [LIMIT {number | ALL}]  [OFFSET number]
*/


/*      http://www.postgresqltutorial.com/postgresql-limit  */

DROP TABLE IF EXISTS film CASCADE;
CREATE TABLE film (id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL);

INSERT INTO film(title) VALUES ('Star Wars: The Last Jedi'),
                               ('Beauty and the Beast'),
                               ('The Fate of the Furious'),
                               ('Despicable Me 3'),
                               ('Jumanji: Welcome to the Jungle'),
                               ('Spider-Man: Homecoming'),
                               ('Wolf Warrior 2'),
                               ('Guardians of the Galaxy Vol. 2'),
                               ('Thor: Ragnarok'),
                               ('Wonder Woman');


SELECT max(id) FROM film;
/*
 max
-----
  10
(1 row)
*/

SELECT id,title FROM film ORDER BY id LIMIT 5;
/*
 id |             title
----+--------------------------------
  1 | Star Wars: The Last Jedi
  2 | Beauty and the Beast
  3 | The Fate of the Furious
  4 | Despicable Me 3
  5 | Jumanji: Welcome to the Jungle
(5 rows)
*/

SELECT id,title FROM film ORDER BY id LIMIT 4 OFFSET 3;
/*
 id |             title
----+--------------------------------
  4 | Despicable Me 3
  5 | Jumanji: Welcome to the Jungle
  6 | Spider-Man: Homecoming
  7 | Wolf Warrior 2
(4 rows)
*/
