all: 01_System \
     02_financial_example \
     03_decimal \
     04_Char \
     05_Array.Sort \
     06_Array.BinarySearch \
     07_Array.Reverse \
     08_Array.Copy \
     09_Array.Exists \
     10_delegate_Action \
     11_Random \
     12_ICloneable


01_System: 01_System.cs Makefile
	mcs 01_System.cs

02_financial_example: 02_financial_example.cs Makefile
	mcs 02_financial_example.cs

03_decimal: 03_decimal.cs Makefile
	mcs 03_decimal.cs

04_Char: 04_Char.cs Makefile
	mcs 04_Char.cs

05_Array.Sort: 05_Array.Sort.cs Makefile
	mcs 05_Array.Sort.cs

06_Array.BinarySearch: 06_Array.BinarySearch.cs Makefile
	mcs 06_Array.BinarySearch.cs

07_Array.Reverse: 07_Array.Reverse.cs Makefile
	mcs 07_Array.Reverse.cs

08_Array.Copy: 08_Array.Copy.cs Makefile
	mcs 08_Array.Copy.cs

09_Array.Exists: 09_Array.Exists.cs Makefile
	mcs 09_Array.Exists.cs

10_delegate_Action: 10_delegate_Action.cs Makefile
	mcs 10_delegate_Action.cs

11_Random: 11_Random.cs Makefile
	mcs 11_Random.cs

12_ICloneable: 12_ICloneable.cs Makefile
	mcs 12_ICloneable.cs


clean:
	rm -v 01_System.exe \
          02_financial_example.exe \
          03_decimal.exe \
          04_Char.exe \
          05_Array.Sort.exe \
          06_Array.BinarySearch.exe \
          07_Array.Reverse.exe \
          08_Array.Copy.exe \
          09_Array.Exists.exe \
          10_delegate_Action.exe \
          11_Random.exe \
          12_ICloneable.exe
