all: gc1

gc1: gc1.cpp
	g++ -g -o gc1 gc1.cpp -lX11

gc2: gc2.cpp
	g++ -g -o gc2 gc2.cpp -lX11

gc3: gc3.cpp
	g++ -g -o gc3 gc3.cpp -lX11

gc4: gc4.cpp
	g++ -g -o gc4 gc4.cpp -lX11

gc5: gc5.cpp
	g++ -g -o gc5 gc5.cpp -lX11

gc6: gc6.cpp
	g++ -g -o gc6 gc6.cpp -lX11

gc7: gc7.cpp
	g++ -g -o gc7 gc7.cpp -lX11

gc8: gc8.cpp
	g++ -g -o gc8 gc8.cpp -lX11

gc9: gc9.cpp
	g++ -g -o gc9 gc9.cpp -lX11


clean:
	rm -v gc{1,2,3,4,5,6,7,8,9} \
          gc1{0,1,2,3,4,5,6,7,8,9}
