all: gc1

gc1: gc1.cpp
	g++ -g -o gc1 gc1.cpp -lX11

gc2: gc2.cpp
	g++ -g -o gc2 gc2.cpp -lX11

gc3: gc3.cpp
	g++ -g -o gc3 gc3.cpp -lX11

gc4: gc4.cpp
	g++ -g -o gc4 gc4.cpp -lX11

gc5: gc5.cpp
	g++ -g -o gc5 gc5.cpp -lX11


clean:
	rm -v gc{1,2,3,4,5,6,7,8,9} \
          gc1{0,1,2,3,4,5,6,7,8,9}
